### PR TITLE
Add object creation question

### PR DESCRIPTION
**Pull request by NovemberZulu**
This question is much easier than exiting mind-blowing stuff, but I still think it is fun.

I also removed what looks like an extra empty line.

### CODE REVIEW

**Comment by 0xd34df00d** [comment]
Lol I forgot this repo exists. Gotta add a few more examples I've stumbled upon since I created it.

Thanks for the contribution! Your example is indeed fun and it was, in fact, a source of some confusion back somewhere I worked a few years ago.

**Comment by NovemberZulu** [comment]
First of all, it is great to know that you are alive! As for this repo, I occasionally link to it to explain why I think C++ is an extremely complicated language, I am surprised it is not more popular.

And last but not least -- the answer is correct, isn't it? I am asking because, well, I don't know C++.

**Comment by 0xd34df00d** [comment]
Sorry for the long reply. I've been hyperfocusing on some other projects lately (as much as finishing all exercises in a textbook by the year end counts as a project). But yeah, I'm alive still :)

> And last but not least -- the answer is correct, isn't it? I am asking because, well, I don't know C++.

The answer is indeed correct as much as I can tell (because neither do I know C++).

There are some fun edge cases though related to this question, but for the case where you're having an array of things — that's what's C++23's `std::start_lifetime_as_array` is for, and that's what I've briefly touched [somewhat recently](https://0xd34df00d.me/posts/2024/09/naive-nfas.html#but-what-about-c-2) (the para starting with "As a side quest").

> As for this repo, I occasionally link to it to explain why I think C++ is an extremely complicated language, I am surprised it is not more popular.
> link

I noticed quite a few folks starring it last few weeks. Shall I (thank|blame) you for that?

**Comment by NovemberZulu** [comment]
> Sorry for the long reply

Absolutely no worries!

> The answer is indeed correct as much as I can tell (because neither do I know C++).

Thank you!

> I noticed quite a few folks starring it last few weeks. Shall I (thank|blame) you for that?

I did mentioned it a few times on LinkedIn, and the timing seem to match, but correlation does not imply causation, and I am not an influencer/blogger/etc., just a guy who does software engineering for a living.

EDIT: formatting

**Pull request merged**
